spring:
  application:
    name: saki-ai-code-tool-backend
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/saki_ai_code_tool?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: SaKi20251013
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: SaKi20251013
      ttl: 3600 # 缓存过期时间（秒）
      username: default
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.saki.sakiaicodetoolbackend.controller
mybatis-flex:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    logic-delete-column: is_delete
    deleted-value-of-logic-delete: 1
    normal-value-of-logic-delete: 0
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# 监控
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always